tunnel: a81f971c-0bbf-46f5-a212-f21c66475617
credentials-file: /etc/cloudflared/a81f971c-0bbf-46f5-a212-f21c66475617.json

ingress:
  - hostname: bcflame.online
    service: https://nginx
    originRequest:
      noTLSVerify: true
  
  - hostname: www.bcflame.online
    service: https://nginx
    originRequest:
      noTLSVerify: true

  - hostname: api.bcflame.online
    service: https://nginx
    originRequest:
      noTLSVerify: true

  - service: http_status:404
