tunnel: a81f971c-0bbf-46f5-a212-f21c66475617
credentials-file: /etc/cloudflared/a81f971c-0bbf-46f5-a212-f21c66475617.json

ingress:
  - hostname: bcflame.online
    service: http://nginx:80
  
  - hostname: www.bcflame.online
    service: http://nginx:80

  - hostname: api.bcflame.online
    service: http://nginx:80

  - service: http_status:404
